working_directory: /usr/src/app
# the netrc_filename value must be a fully-qualified name
# netrc_filename: /usr/src/app/test_netrc
# operational value is ivo://cadc.nrc.ca/caom2repo
# tardis value is ivo://cadc.nrc.ca/ams
resource_id: ivo://cadc.nrc.ca/sc2repo
todo_file_name: todo.txt
proxy_file_name: /usr/src/app/cadcproxy.pem
# values True False
use_local_files: True
# values DEBUG INFO WARN ERROR
logging_level: DEBUG
# values True False
log_to_file: True
# fully qualified name for a directory to write log files
log_file_directory: /usr/src/app/logs
# ad stream value - sorry
stream: raw
# how to control the work that gets done
task_types: 
  - remote
features:
  supports_composite: False
  run_in_airflow: False
  use_file_names: True
